//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITP245_Agile_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.Activities = new HashSet<Activity>();
        }
    
        public int TaskId { get; set; }
        public Nullable<int> ProjectMemberId { get; set; }
        public string Name { get; set; }
        public int DueDateKey { get; set; }
        public int StatusId { get; set; }
        public string Comment { get; set; }
        public Nullable<int> CourseId { get; set; }
        public string Description { get; set; }
        public Nullable<int> CompletedDateKey { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> StudentId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual DimDate DimDate { get; set; }
        public virtual DimDate DimDate1 { get; set; }
        public virtual Project Project { get; set; }
        public virtual ProjectMember ProjectMember { get; set; }
        public virtual Student Student { get; set; }
    }
}
