//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITP245_Sports_Model
{
    using System;
    
    public enum GameStatus : int
    {
        Win = 1,
        Loss = 2,
        Draw = 3
    }
}
